bugfixes in addconnection (spaces in ssids)

diff --git a/source/home_p_bin/addconnection b/source/home_p_bin/addconnection
--- a/source/home_p_bin/addconnection
+++ b/source/home_p_bin/addconnection
@@ -5,11 +5,13 @@
 WIFI_SSID="${1}"
 WIFI_PASSWORD_FILE="/home/p/wifi_password"
 
-[ -z ${WIFI_SSID} ] && { echo "SSID is missing."; exit 1; }
+[ ! "${WIFI_SSID}" ] && { echo "Error: The SSID of the wifi network is missing."; exit 1; }
 
-echo "Creating new wifi connection for SSID: "${WIFI_SSID}""
-read -p "Enter wifi password for "${WIFI_SSID}": " WIFI_PASSWORD
-echo "802-11-wireless-security.psk:"${WIFI_PASSWORD}""  > ${WIFI_PASSWORD_FILE}
+echo
+echo "> Creating new wifi connection for SSID: "${WIFI_SSID}""
+read -p "> Enter wifi password for "${WIFI_SSID}": " WIFI_PASSWORD
+echo
+echo "802-11-wireless-security.psk:"${WIFI_PASSWORD}""  > "${WIFI_PASSWORD_FILE}"
 
 sudo nmcli connection add type wifi ifname wlan0 ssid "${WIFI_SSID}" connection.id "${WIFI_SSID}"
 sudo nmcli connection modify "${WIFI_SSID}" connection.autoconnect 1
@@ -19,10 +21,12 @@ sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.key-mgmt wp
 sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.auth-alg open
 #sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.psk ${WIFI_PASSWORD}
 #sudo nmcli connection modify "${WIFI_SSID}" 802-11-wireless-security.psk password-file 
-echo "Trying to activate the new connection."
-echo "This connection to razpass will propably disconnect."
-read -p "Press enter to continue..."
-sudo nmcli connection up "${WIFI_SSID}" passwd-file ${WIFI_PASSWORD_FILE}
+echo
+echo "> Trying to activate the new connection."
+echo "> This connection to razpass will propably disconnect."
+read -p "> Press enter to continue..."
+echo
+sudo nmcli connection up "${WIFI_SSID}" passwd-file "${WIFI_PASSWORD_FILE}"
 #rm /home/p/wifi_password
 
 
